#配置数据源
spring:
  application:
    name: yshop-system
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/yshop?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat

      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    #连接超时时间
    timeout: 5000

# 是否限制单用户登录
single:
  login: false

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#是否允许生成代码，生产环境设置为false
generator:
  enabled: false

#如果生产环境要开启swagger，需要配置请求地址
#springfox:
#  documentation:
#    swagger:
#      v2:
#        host: # 接口域名或外网ip

#是否开启 swagger-ui，生产环境默认不开启
swagger:
  enabled: false
  title: yshop商城管理后台API
  serverUrl: http://127.0.0.1:8000
  version: 2.2

# 文件存储路径
# 文件存储路径
#  1.localUrl为空的话上传文件会走七牛云，清转向文档看七牛云配置
#  2.如果想文件存在本地，并通过本地代理出去请填写localUrl： http://127.0.0.1:8000为本服务的ip+端口号
#     线上的地址就是你通过nginx代理http://127.0.0.1:8000出来的地址。鉴于群里很多问的这里做个说明不在赘述
file:
  path: /hyjfdata/data/mitu/upload/file/
  avatar: /hyjfdata/data/mitu/upload/avatar/
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
  localUrl: http://39.98.139.163:8000

yshop:
  # 订单号生成配置  数据中心的id 每一个jar包都需要不同
  snowflake:
    datacenterId: 1
  # 快鸟物流查询配置
  express:
    enable: true
    appId: 1607734
    appKey: 81f43a2e-f504-45c4-9b54-2637d59f8190
  apiUrl: http://localhost:8009/api
  hApi: https://localhost:8000
  wechatCode: http://localhost:8000/upload/qrcode_for_gh_2ac8f422a79f_258.jpg
  miniAppID:

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      mapper-locations: classpath*:mapper/**/*Mapper.xml

# 日志配置
logging:
  config: classpath:logback-spring.xml
  file: /hyjfdata/log/mitu/${spring.profiles.active}/ststem.log
  file.max-size: 50MB
  #当参数定义int简单类型并使用@apiModelPerperty标签时,如果不指名example属性,会导致swagger类型转换错误,信息如下
  #java.lang.NumberFormatException: For input string: ""
  level.io.swagger.models.parameters.AbstractSerializableParameter: error

# 叮叮配置
dingding:
  log:
    enabled: true
    accessToken: f6b51497a6fa18dd05526c41533cedb5e4445e77de37733c68a0e0de01dd4b43
    secret: SECac2971ad758c4d5d20908a4aa01e5e286248f93abd854e2199632560fd5f95e0

#spring rocket mq
rocketmq:
  nameServer: newdev1-3:9876
  producer:
    group: mitu-test