#配置数据源
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://39.98.139.163:33306/mitu?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      #url: jdbc:log4jdbc:mysql://localhost:3306/yxshop?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: dbwrite
      password: aAR!Q23AUP!ogk$J

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
  redis:
    #数据库索引
    database: 1
    host: 10.10.2.221
    port: 6379
    password: hyjf@2020
    #连接超时时间
    timeout: 5000
#配置rocketmq
rocketmq:
  nameServer: 39.100.232.229:9876
  producer:
    group: mitu-dev
    sendMessageTimeout: 300000

# 是否限制单用户登录
single:
  login: true

#jwt
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: token:m-online-token

# 日志配置
logging:
  config: classpath:logback-spring.xml
  file: /hyjfdata/log/mitu/${spring.profiles.active}/api.log
  file.max-size: 50MB
  #当参数定义int简单类型并使用@apiModelPerperty标签时,如果不指名example属性,会导致swagger类型转换错误,信息如下
  #java.lang.NumberFormatException: For input string: ""
  level.io.swagger.models.parameters.AbstractSerializableParameter: error

## 叮叮配置
#dingding:
#  log:
#    enabled: true
#    accessToken: f6b51497a6fa18dd05526c41533cedb5e4445e77de37733c68a0e0de01dd4b43
#    secret: SECac2971ad758c4d5d20908a4aa01e5e286248f93abd854e2199632560fd5f95e0


#是否开启 swagger-ui
swagger:
  enabled: true
  title: yshop商城移动端API
  serverUrl: http://localhost:8009
  version: 2.2

# 文件存储路径
#  1.localUrl为空的话上传文件会走七牛云，清转向文档看七牛云配置
#  2.如果想文件存在本地，并通过本地代理出去请填写localUrl： http://127.0.0.1:8009为本服务的ip+端口号
#     线上的地址就是你通过nginx代理http://127.0.0.1:8009出来的地址。鉴于群里很多问的这里做个说明不在赘述
file:
  path: D:\yshop\file\
  avatar: D:\yshop\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
  localUrl:


yshop:
  # 订单号生成配置  数据中心的id 每一个jar包都需要不同
  snowflake:
    datacenterId: ${spring.datacenterId}
  isProd: false
  #通知相关配置
  notify:
    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      # 如果是腾讯云短信，则设置active的值tencent
      # 如果是阿里云短信，则设置active的值aliyun
      active: aliyun
      sign: yshop
      template:
        - name: paySucceed
          templateId: 156349
        - name: captcha
          templateId: SMS_182680588
        - name: ship
          templateId: 158002
        - name: refund
          templateId: 159447
      tencent:
        appid: 111111111
        appkey: xxxxxxxxxxxxxx
      aliyun:
        regionId: cn-hangzhou
        accessKeyId:
        accessKeySecret:


  # 快鸟物流查询配置
  express:
    enable: true
    appId: 1607734
    appKey: 81f43a2e-f504-45c4-9b54-2637d59f8190

  #发送邮件配置
  mailsconfig:
    port: 465
    comHost: smtp.qiye.163.com
    #    以下需修改
    sendUser: nixiaoling@hyjf.com
    sendFrom: nixiaoling@hyjf.com
    sendPassword: kid0717Q!@#
    sslEnable: true

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: id_worker
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath*:mapper/**/*Mapper.xml


management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  endpoint:
    health:
      show-details: ALWAYS

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 2
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}

#悟空开放平台地址 模拟：http://smlitsm.tsign.cn:8080    正式http://openapi.tsign.cn:8080：
wukong:
  url: http://smlitsm.tsign.cn:8080/tgmonitor/rest/app!getAPIInfo2
  project:
    id: 4438785109
    secret: 0c0bd9c66d760866bafe89cce9109ac7
  cunzheng:
    url: http://smlcunzheng.tsign.cn:8083/
  # 生成合同的存放路径
  path: /esgin/pdf/
  # 填充模板用个人用户数据
  template:
    user:
     name: 锺强
     idcard: 140000200011043143
